apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 61.2.0
    chart: kube-prometheus-stack-61.2.0
    heritage: Helm
    release: monitoring
  name: monitoring-kube-prometheus-alertmanager
  namespace: monitoring
spec:
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: webhook2dingtalk
  automountServiceAccountToken: true
  externalUrl: 'http://monitoring-kube-prometheus-alertmanager.monitoring:9093'
  image: 'quay.io/prometheus/alertmanager:v0.27.0'
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  portName: http-web
  replicas: 3
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: monitoring-kube-prometheus-alertmanager
  version: v0.27.0
status:
  availableReplicas: 3
  conditions:
    - lastTransitionTime: '2024-08-23T08:20:50Z'
      message: ''
      observedGeneration: 2
      reason: ''
      status: 'True'
      type: Available
    - lastTransitionTime: '2024-08-15T08:49:25Z'
      message: ''
      observedGeneration: 2
      reason: ''
      status: 'True'
      type: Reconciled
  paused: false
  replicas: 3
  unavailableReplicas: 0
  updatedReplicas: 3
