apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 61.2.0
    chart: kube-prometheus-stack-61.2.0
    heritage: Helm
    release: monitoring
  name: monitoring-kube-prometheus-prometheus
  namespace: monitoring
spec:
  additionalScrapeConfigs:
    key: additional-scrape-configs.yaml
    name: monitoring-kube-prometheus-prometheus-scrape-confg
  alerting:
    alertmanagers:
      - apiVersion: v2
        name: monitoring-kube-prometheus-alertmanager
        namespace: monitoring
        pathPrefix: /
        port: http-web
  automountServiceAccountToken: true
  enableAdminAPI: false
  evaluationInterval: 30s
  externalUrl: 'http://172.30.13.86:18938'
  hostNetwork: false
  image: 'quay.io/prometheus/prometheus:v2.53.0'
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: monitoring
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: monitoring
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: monitoring
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      release: monitoring
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: monitoring-kube-prometheus-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: monitoring
  shards: 1
  tsdb:
    outOfOrderTimeWindow: 0s
  version: v2.53.0
  walCompression: true
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2024-08-23T08:35:27Z'
      message: ''
      observedGeneration: 4
      reason: ''
      status: 'True'
      type: Available
    - lastTransitionTime: '2024-08-23T08:35:27Z'
      message: ''
      observedGeneration: 4
      reason: ''
      status: 'True'
      type: Reconciled
  paused: false
  replicas: 1
  selector: >-
    app.kubernetes.io/instance=monitoring-kube-prometheus-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=monitoring-kube-prometheus-prometheus,prometheus=monitoring-kube-prometheus-prometheus
  shardStatuses:
    - availableReplicas: 1
      replicas: 1
      shardID: '0'
      unavailableReplicas: 0
      updatedReplicas: 1
  shards: 1
  unavailableReplicas: 0
  updatedReplicas: 1
