kind: Cluster
name: local-cluster
apiVersion: kind.x-k8s.io/v1alpha4
# featureGates:
# any feature gate can be enabled here with "Name": true
# or disabled here with "Name": false
# not all feature gates are tested, however
# "CSIMigration": true
networking:
  # apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  # disableDefaultCNI: true
  # kubeProxyMode: "nftables"
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: TCP
    extraMounts:
      - hostPath: /usr/share/zoneinfo/Asia/Shanghai
        containerPath: /etc/localtime
    # readOnly: true
    # selinuxRelabel: false
