apiVersion: v1
kind: ServiceAccount
metadata:
  name: rolloutexecute-account
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rolloutexecute-role
  namespace: test
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolloutexecute-access-test-namespace
  namespace: test
subjects:
  - kind: ServiceAccount
    name: rolloutexecute-account
    namespace: test
roleRef:
  kind: Role
  name: rolloutexecute-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: rolloutexecute-account-secret
  annotations:
    kubernetes.io/service-account.name: "rolloutexecute-account"
type: kubernetes.io/service-account-token
