apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: webhook2dingtalk
  labels:
    alertmanagerConfig: webhook2dingtalk
  namespace: monitoring
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'dingtalk-webhook'
    routes:
      - receiver: 'dingtalk-webhook'
        matchers:
          - name: alertname
            regex: true
            value: '!Watchdog'
        continue: true
      - receiver: 'null'
        matchers:
          - name: alertname
            value: 'Watchdog'
  receivers:
    - name: 'dingtalk-webhook'
      webhookConfigs:
        - url: 'http://172.30.13.81:8060/dingtalk/webhook/send'
    - name: 'null'
