kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.10.1
  annotations:
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: 10254
      targetPort: prometheus
      nodePort: 29779
    - name: http
      protocol: TCP
      appProtocol: http
      port: 80
      targetPort: http
      nodePort: 80
    - name: https
      protocol: TCP
      appProtocol: https
      port: 443
      targetPort: https
      nodePort: 443
    # if out of nodePort range, need to add flag "    - --service-node-port-range=80-65000" into /etc/kubernetes/manifast/kube-apiserver.yaml
    - name: monitor-tcp-9100
      port: 9100
      targetPort: 9100
      nodePort: 29100
      protocol: TCP
    - name: sentinel-tcp-8718
      port: 8718
      targetPort: 8718
      nodePort: 28718
      protocol: TCP
    - name: seata-tcp-7091
      port: 7091
      targetPort: 7091
      nodePort: 27091
      protocol: TCP
    - name: seata-tcp-8091
      port: 8091
      targetPort: 8091
      nodePort: 28091
      protocol: TCP
    - name: proxied-tcp-9080
      port: 9080
      targetPort: 9080
      nodePort: 29080
      protocol: TCP
    - name: proxied-tcp-58080
      port: 58080
      targetPort: 58080
      nodePort: 28080
      protocol: TCP
    - name: tcp-debug-auth
      port: 18050
      targetPort: 18050
      nodePort: 18050
      protocol: TCP
    - name: tcp-debug-gen
      port: 18051
      targetPort: 18051
      nodePort: 18051
      protocol: TCP
    - name: tcp-debug-resource
      port: 18052
      targetPort: 18052
      nodePort: 18052
      protocol: TCP
    - name: tcp-debug-system
      port: 18053
      targetPort: 18053
      nodePort: 18053
      protocol: TCP
    - name: tcp-debug-terminal
      port: 18054
      targetPort: 18054
      nodePort: 18054
      protocol: TCP
    - name: tcp-debug-translate
      port: 18055
      targetPort: 18055
      nodePort: 18055
      protocol: TCP
    - name: tcp-debug-account
      port: 18056
      targetPort: 18056
      nodePort: 18056
      protocol: TCP
    - name: tcp-debug-ip
      port: 18057
      targetPort: 18057
      nodePort: 18057
      protocol: TCP
    - name: tcp-debug-login
      port: 18058
      targetPort: 18058
      nodePort: 18058
      protocol: TCP
    - name: tcp-debug-counter
      port: 18059
      targetPort: 18059
      nodePort: 18059
      protocol: TCP
    - name: tcp-debug-content
      port: 18060
      targetPort: 18060
      nodePort: 18060
      protocol: TCP
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
