# create tcp-proxy with ingress
# https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  9100: "default/monitor-cs:9100"
  8718: "default/sentinel-cs:8718"
  7091: "default/seata-cs:7091"
  8091: "default/seata-cs:8091"
  9080: "test/imx-terminal-control-center:9080"
  58080: "test/imx-terminal-control-center:8080"
  18050: "test/imx-auth:18050"
  18051: "test/imx-gen:18051"
  18052: "test/imx-resource:18052"
  18053: "test/imx-system:18053"
  18054: "test/imx-terminal-control-center:18054"
  18055: "test/imx-translate:18055"
  18056: "test/imx-ws-account:18056"
  18057: "test/imx-ws-ip:18057"
  18058: "test/imx-ws-login:18058"
