## Request timeout
# timeout: 5s

## Customizable templates path
templates:
  - /etc/prometheus-webhook-dingtalk/template.tmpl
  # - contrib/templates/legacy/template.tmpl
## You can also override default template using `default_message`
## The following example to use the 'legacy' template from v0.3.0
# default_message:
#   title: '{{ template "legacy.title" . }}'
#   text: '{{ template "legacy.content" . }}'

## Targets, previously was known as "profiles"
targets:
  webhook:
    url: https://oapi.dingtalk.com/robot/send?access_token=6421ad19d90985c78fb840b505903378ad222aded7ac3af16b8130aeeb9e2257
    # Customize template content
    message:
      title: '{{ "Prometheus" }}'
      text: '{{ template "ding.link.content" . }}'
    mention:
      mobiles: ['13138686340']
